### ISSUE TITLE
configure: error: Please reinstall the libzip distribution

### ISSUE THREAD

**Issue by lpeliberty** [rezsolt/docker-php-apache-mysql-composer#8]
Hello,
you have an error on building containers : 
`configure: error: Please reinstall the libzip distribution`

To fix this, plz change the following line in `.docker/phpApache`
```
RUN apt-get update \
    && apt-get install -y --no-install-recommends git zlib1g-dev libzip-dev zip unzip
```

**Comment by rezsolt** [comment]
Thank you lpeliberty to report this bug.
I fixed it today and also merged to master: 8960b54c2d963ada531b2b97e8359c6a29453859
